# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CLIR 2016-2018 Annual Report
author: Wayne Graham
email: wayne.graham@gmail.com
twitter_username: wayne_graham
github_username:  waynegraham
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
baseurl: "/recipes"
url: "https://waynegraham.github.io/2017AnnualReport"
google_analytics_key:

paginate: 20
paginate_path: "/:num/"
permalink: pretty

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-seo-tag

feed:
  path: atom.xml

exclude:
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
